#!/usr/bin/env python3
from pathlib import Path
import sys
import yaml

PAGE_SIZE_DEFAULT = 64

def as_int(value):
    if isinstance(value, int):
        return value
    return int(str(value), 0)

def load_registry(path):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)

def address_start(page, page_size):
    return page * page_size

def address_end(page, page_size):
    return ((page + 1) * page_size) - 1

def code_hex(value, width):
    return f"`0x{value:0{width}X}`"

def page_range(start, end):
    if start == end:
        return code_hex(start, 3)
    return f"`0x{start:03X}–0x{end:03X}`"

def address_range(start_page, end_page, page_size):
    return f"`0x{address_start(start_page,page_size):04X}–0x{address_end(end_page,page_size):04X}`"

def esc(text):
    return str(text or "").replace("|", r"\|")

def render(data):
    page_size = int(data.get("page_size", PAGE_SIZE_DEFAULT))
    total_pages = int(data["total_pages"])
    default_platform = data.get("default_platform", "Atari 2600")
    allocations = data["allocations"]

    normalized = []
    used = set()
    for item in allocations:
        item = dict(item)
        item["_start"] = as_int(item["pages"]["start"])
        item["_end"] = as_int(item["pages"]["end"])
        normalized.append(item)
        used.update(range(item["_start"], item["_end"] + 1))

    normalized.sort(key=lambda i: (i["_start"], i["_end"], i["title"]))

    lines = [
        "# SaveKey / AtariVox Allocation List",
        "",
        "> **Generated file.** Do not edit this file directly. Edit [`allocations.yaml`](allocations.yaml) instead.",
        "",
        f"The canonical data in this repository is `allocations.yaml`. Address ranges below are derived from {page_size}-byte page numbers.",
        "",
        "## Allocated ranges",
        "",
        "| Pages | Address range | Platform | Assignment | Developer | Kind |",
        "|---:|---:|---|---|---|---|",
    ]
    for item in normalized:
        s, e = item["_start"], item["_end"]
        lines.append(
            f"| {page_range(s,e)} | {address_range(s,e,page_size)} | "
            f"{esc(item.get('platform', default_platform))} | {esc(item['title'])} | "
            f"{esc(item.get('developer',''))} | {esc(item.get('kind','game'))} |"
        )

    free = []
    p = 0
    while p < total_pages:
        if p in used:
            p += 1
            continue
        s = p
        while p + 1 < total_pages and (p + 1) not in used:
            p += 1
        free.append((s, p))
        p += 1

    lines += [
        "",
        "## Currently unallocated ranges",
        "",
        "These ranges are calculated from the registry. Always check open pull requests and issues before assuming a range is safe to claim.",
        "",
        "| Pages | Address range | Pages available |",
        "|---:|---:|---:|",
    ]
    for s, e in free:
        lines.append(f"| {page_range(s,e)} | {address_range(s,e,page_size)} | {e-s+1} |")

    source = data.get("source", {})
    lines += [
        "",
        "## Source",
        "",
        f"Initial import: {source.get('name','')}",
        "",
        source.get("url",""),
        "",
        f"Source last updated: {source.get('source_last_updated','unknown')}",
        "",
    ]

    corrections = [i for i in normalized if i.get("source_correction")]
    if corrections:
        lines += ["## Source notes", ""]
        for item in corrections:
            lines.append(f"- **{item['title']}**: {item['source_correction']}")
        lines.append("")

    return "\n".join(lines)

def main():
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "allocations.yaml")
    dst = Path(sys.argv[2] if len(sys.argv) > 2 else "ALLOCATIONS.md")
    dst.write_text(render(load_registry(src)), encoding="utf-8")
    print(f"Wrote {dst}")

if __name__ == "__main__":
    main()
